### PR TITLE
react-runner-with-swc (Need to create a new branch)

### PR DESCRIPTION
**Pull request by Mrxyy**
+  You can compile the code to ES5

### CODE REVIEW

**Comment by nihgwu** [comment]
what's the motivation?

**Comment by Mrxyy** [comment]
SWC can compile lower-level code to support more browsers.

**Comment by nihgwu** [comment]
This package supports modern browsers(ES6), don't think WASM has broader support, and we use `sucrase` instead of Babel for smaller bundle size, I believe SWC will bloat it a lot(although it's loaded separately), and `sucrase` is already fast enough and maybe faster than swc in this case because of runtime of WASM

**Comment by Mrxyy** [comment]
> This package supports modern browsers(ES6), don't think WASM has broader support, and we use `sucrase` instead of Babel for smaller bundle size, I believe SWC will bloat it a lot(although it's loaded separately), and `sucrase` is already fast enough and maybe faster than swc in this case because of runtime of WASM

My use case is as follows: I created a custom component on our low-code platform in the modern browser environment of the canvas editing mode. However, when the application is actually deployed, there is no code compilation process and instead it uses the previously compiled results.

**Comment by Mrxyy** [comment]
> > This package supports modern browsers(ES6), don't think WASM has broader support, and we use `sucrase` instead of Babel for smaller bundle size, I believe SWC will bloat it a lot(although it's loaded separately), and `sucrase` is already fast enough and maybe faster than swc in this case because of runtime of WASM
> 
> My use case is as follows: I created a custom component on our low-code platform in the modern browser environment of the canvas editing mode. However, when the application is actually deployed, there is no code compilation process and instead it uses the previously compiled results.

It is indeed inappropriate to do so when running in a browser.

**Pull request closed without merging**
