### PR TITLE
chore(deps): update react-simple-code-editor to ^0.13.1

### LINKED ISSUE #123: [Feature]: Add React 18 support for `react-live-runner`
## **Is your feature request related to a problem? Please describe.**

Last npm release from `react-simple-code-editor` is `v0.11.0`, almost 2 years ago.
It's better to replace it with another React code editor that supports React 18.

## **Describe the solution you'd like**

Replace `react-simple-code-editor`.

### PR DESCRIPTION
**Pull request by sabertazimi**
[React simple code editor](https://github.com/react-simple-code-editor/react-simple-code-editor) has shipped to TypeScript
and updated its `peerDependencies`.

Close #123.

### CODE REVIEW

**Comment by nihgwu** [comment]
hey thank you for your contribution, can you fix the types

**Comment by sabertazimi** [comment]
> hey thank you for your contribution, can you fix the types

Fixed.

**Comment by nihgwu** [comment]
@sabertazimi published 1.0.5

**Comment by sabertazimi** [comment]
> @sabertazimi published 1.0.5

Thx a lot.

**Pull request merged**
